services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /home/brzpv/PhpstormProjects/online-shop-brzpv/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/brzpdcv/PhpstormProjects/online-shop-brzpv:/var/www/html

  php-fpm:
    container_name: php-fpm
    build: /home/brzpv/PhpstormProjects/online-shop-brzpv/docker/php
    volumes:
      - /home/brzpv/PhpstormProjects/online-shop-brzpv:/var/www/html

  db:
    image: postgres:13.1
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5431:5432
